Feature/pmt placement
WCTE/WCSim pull request #9
Opened 2023-02-27 08:04 UTC by kmtsui

Prerequisite: Developed with geant4.10.05.p01 and root_v6.22.06, need to be tested with older (official) software versions.

Place the PMTs in the detector one by one instead of using the default replica method.

Several new functionalities for more flexible PMT placement:
1. Small fluctuation of placement around the nominal positions
2. Change the ID radius for ID PMT placement. Currently we can specify the radius change at the top, middle and bottom of barrel, and interpolate the detector radius at different heights.
3. Able to read tabulated PMT positions from a file and use them in simulation. To be most flexible, the table contains the X,Y,Z positions, but during the placement process, they are converted to cylindrical coordinates (z,theta), and the radial coordinate is automatically tuned such that the PMT is always touching the blacksheet.

The new macro commands to use these new functions are listed in WCSim.mac

2023-03-07 00:39 UTC, pdeperio requested changes

2023-03-07 00:39 UTC, pdeperio commented on WCSim.mac
> +#/WCSim/WCgeom nuPRISMShort_mPMT
Lauren has created a new WCTE dedicated macro ([macros/nuPRISMBeamTest.mac](https://github.com/WCTE/WCSim/blob/nuPRISM/develop/macros/nuPRISMBeamTest.mac)) to simplify and clarify for new users. could you move this to there (and keep just general commands that would work for any geometry here)?

2023-03-07 00:39 UTC, pdeperio commented on include/GdNeutronHPCapture.hh
> +#include "G4SystemOfUnits.hh"
seems to be duplicated in https://github.com/WCTE/WCSim/pull/7. for next time, should try to consolidate common changes in a single PR to be merged first, and base the rest on it.

2023-03-07 00:40 UTC, pdeperio requested changes
also add link to slides or add descriptive diagrams and validation plots here.

2023-03-07 00:45 UTC, pdeperio commented on include/GdNeutronHPCapture.hh
> +#include "G4SystemOfUnits.hh"
actually, possible to split out PR now? will help Tom reviewing later when we merge to WCSim/WCSim

2023-03-07 07:46 UTC, pdeperio commented on include/GdNeutronHPCapture.hh
> +#include "G4SystemOfUnits.hh"
resolved in https://github.com/WCTE/WCSim/pull/10

@kmtsui please write this kind of message when resolving specific comments in another PR

2023-03-11 02:59 UTC, pdeperio commented
can you add timing benchmarks? e.g. comparing simulation time with following configs:

1. original method
2. new code, but no variation
3. different variations of geometry

?

2023-03-13 04:24 UTC, kmtsui commented
Simulation time of 100 events of 500 MeV electron gun:
1. original method: User=105.59s Real=106.25s Sys=0.09s
2. new code, but no variation: User=98.73s Real=99.33s Sys=0.07s
3. Using `/WCSim/PMT/PositionVariation 10 mm`, `/WCSim/PMT/TankRadiusChange 0 100 200 mm`, `/WCSim/PMT/PositionFile mPMT-configfiles/mPMTconfig_Position_WCTE.txt`: User=99.94s Real=100.55s Sys=0.06s

No significant difference is observed.

2023-03-14 05:12 UTC, pdeperio commented
you also previously showed some validation by running photon simulation and counting hits. could you also do a more direct validation using the true hit position (i.e. showing that true hit position comes out as expected from the chosen variation)? and post the plots or link here?

2023-03-16 07:04 UTC, kmtsui commented
Hit plots from true hit positions

1. original method 
<img width="991" alt="image" src="https://user-images.githubusercontent.com/19830271/225533486-49cdc6b3-892b-4c84-ba91-6aa491bdd753.png">
2. new code, but no variation
<img width="988" alt="image" src="https://user-images.githubusercontent.com/19830271/225533616-af72fc0a-4321-4416-86b6-3d347606762f.png">
3. new code with variations same as above
<img width="986" alt="image" src="https://user-images.githubusercontent.com/19830271/225540004-ab8863a8-c6bd-4fae-ba9c-5e26528fc321.png">

2023-03-21 22:34 UTC, pdeperio commented
thanks @kmtsui. do you have a histogram of the `true hit position - expected position from geometry input` difference? (i just noticed you mention in first post:
> This reproduces the nominal PMT positions with insignificant differences (~10^-9).
but i guess this is just based on geometry info and not actual hit info?

2023-03-21 22:37 UTC, pdeperio approved these changes

2023-03-23 14:41 UTC, laurenanthony2 commented on WCSim.mac
Does this method work with all of the geometries? The official macro for WCTE is now in /macros/nuPRISMBeamTest.mac. The addition of the ReplicaREplacement function should also be added there too?

2023-03-24 02:36 UTC, kmtsui commented on WCSim.mac
Yes the method should work for all geometries, but will need e.g. the corresponding position table

2023-03-24 12:02 UTC, laurenanthony2 commented on WCSim.mac
Could you add a comment in the WCTE macro, or in the README to clarify that the current table corresponds to the nuPRISMBeamTest_16cShort geometry? It might be obvious here, but just so it's clear to other users.

2023-03-27 10:19 UTC, laurenanthony2 approved these changes

2023-03-31 02:21 UTC, merged